# Generated by Django 5.0.2 on 2024-03-09 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0008_cartitems_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='subtotal',
        ),
    ]
