# Generated by Django 5.0.2 on 2024-03-10 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0012_alter_cartitems_cart_alter_coupon_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='ecommerceApp.cart'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount_price',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='is_expired',
            field=models.BooleanField(default=100),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='ecommerceApp.product'),
        ),
    ]
