# Generated by Django 5.0.2 on 2024-03-12 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0015_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='checkout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='ecommerceApp.cart'),
        ),
    ]
