# Generated by Django 5.0.2 on 2024-03-12 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0016_checkout_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='checkout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='ecommerceApp.cart'),
        ),
    ]
