# Generated by Django 5.0.2 on 2024-03-12 16:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0020_alter_cart_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CODTransaction',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RazorpayTransaction',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('razor_pay_order_id', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('razor_pay_payment_id', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('razor_pay_payment_signature', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='cart',
            name='razor_pay_order_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='razor_pay_payment_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='razor_pay_payment_signature',
        ),
        migrations.AlterField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerceApp.coupon'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='cod_transactions',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cart_cod_transactions', to='ecommerceApp.codtransaction'),
        ),
        migrations.AddField(
            model_name='cart',
            name='razorpay_transactions',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cart_razorpay_transactions', to='ecommerceApp.razorpaytransaction'),
        ),
    ]
