# Generated by Django 5.0.2 on 2024-03-12 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0022_alter_cart_cod_transactions_alter_cart_coupon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cod_transactions',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='razorpay_transactions',
        ),
        migrations.AddField(
            model_name='codtransaction',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CODTransaction', to='ecommerceApp.cart'),
        ),
        migrations.AddField(
            model_name='razorpaytransaction',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RazorpayTransaction', to='ecommerceApp.cart'),
        ),
    ]
