# Generated by Django 5.0.2 on 2024-03-12 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0023_remove_cart_cod_transactions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codtransaction',
            old_name='cart',
            new_name='cod',
        ),
        migrations.RenameField(
            model_name='razorpaytransaction',
            old_name='cart',
            new_name='rezorpay',
        ),
    ]
