# Generated by Django 5.0.2 on 2024-03-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0024_rename_cart_codtransaction_cod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razorpaytransaction',
            name='razor_pay_order_id',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='razorpaytransaction',
            name='razor_pay_payment_id',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='razorpaytransaction',
            name='razor_pay_payment_signature',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
