# Generated by Django 5.0.2 on 2024-03-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0026_rename_cod_codtransaction_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='cart',
            name='payment_methods',
            field=models.CharField(blank=True, default='Razorpay', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='razorpaytransaction',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
