# Generated by Django 5.0.2 on 2024-03-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0033_alter_codtransaction_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='razorpaytransaction',
            name='razor_pay_payment_id',
        ),
        migrations.RemoveField(
            model_name='razorpaytransaction',
            name='razor_pay_payment_signature',
        ),
    ]
