# Generated by Django 5.0.2 on 2024-03-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0034_remove_razorpaytransaction_razor_pay_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='razorpaytransaction',
            name='razor_pay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='razorpaytransaction',
            name='razor_pay_payment_signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
