# Generated by Django 5.0.2 on 2024-03-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0038_cart_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_id',
            field=models.CharField(max_length=100),
        ),
    ]
