# Generated by Django 5.0.2 on 2024-03-18 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0041_wishlish'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wishlish',
            new_name='Wishlist',
        ),
    ]
