# Generated by Django 5.0.2 on 2024-03-20 11:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0042_rename_wishlish_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('order_placed', 'Order Placed'), ('order_received', 'Order Received'), ('products_picked', 'Products Picked'), ('products_packed', 'Products Packed'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered')], default='order_placed', max_length=20)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_status', to='ecommerceApp.cart')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
