# Generated by Django 5.0.2 on 2024-03-20 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0046_alter_deliverystatus_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverystatus',
            name='return_date',
        ),
    ]
