# Generated by Django 5.0.2 on 2024-03-28 08:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0058_alter_cartitems_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Shipped', 'Shipped'), ('On the way', 'On the way'), ('Delivered', 'Delivered')], max_length=20),
        ),
        migrations.AlterField(
            model_name='returnstatus',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('In Transit', 'In Transit'), ('Return Received', 'Return Received')], default='Requested', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderCancel',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancellation_reason', models.TextField()),
                ('cancellation_date', models.DateTimeField(auto_now_add=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_cancel', to='ecommerceApp.cart')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
