# Generated by Django 5.0.2 on 2024-03-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0059_alter_cart_status_alter_returnstatus_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnstatus',
            name='cart',
        ),
        migrations.DeleteModel(
            name='OrderCancel',
        ),
        migrations.DeleteModel(
            name='ReturnStatus',
        ),
    ]
