# Generated by Django 4.0.6 on 2024-04-15 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0068_product_brand_product_material'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
