# Generated by Django 5.0.2 on 2024-03-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
